# Default values for besu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imagePullPolicy: IfNotPresent
image:
  besu:
    repository: hyperledger/besu
    tag: latest
  orion:
    repository: pegasyseng/orion
    tag: develop

namespace:
  consortium: consortium
  members: members

# config specific to node-statefulset ie. replicas, storage etc
node:
  replicaCount: 1
  pvcSizeLimit: "1Gi"
  pvcStorageClass: "standard"
  memRequest: "1024Mi"
  memLimit: "2048Mi"
  cpuRequest: "100m"
  cpuLimit: "500m"

validators:
  pvcSizeLimit: "1Gi"
  pvcStorageClass: "standard"
  memRequest: "1024Mi"
  memLimit: "2048Mi"
  cpuRequest: "100m"
  cpuLimit: "500m"
  validator1:
    privateKey: "0fd4aecd8f02b24f468325aa06e1428ab8076d283bac3ed804c9f70187dedb63"
    publicKey: "0x5d812c3c25ff398ab416968fce9009c2be7ed70a87abc8ea30bd667ce17a9287a6341fbf6ce757bb8148436c39c71296639ea81afcc94cdf908b6e1344f26188"

  validator2:
    privateKey: "47c63c0afd1a85b16915934a2d75cf5a0d3bd13c509d6ee9d7ef1315a36bdc0a"
    publicKey: "0xb2fba529681ea7f4619556753d40c8689b936fb1c621bc91f94d2938eb58c285d4911457ae4887b9c3bd593b2d608d319c6dc384d6acae2d043a4657029178d3"

  validator3:
    privateKey: "35dcc853354b24e98889fa4b2e214d5e92e759ef8312bb6a444bad3182187b68"
    publicKey: "0x00b20ab6a385a2403d64637b3d93cb6d83215a08f29adb6feb4b8bf03387b734444e8b060f53150dea4b9b897823540d19918c13d6f57a5153d190b5fad7bf51"

  validator4:
    privateKey: "d38e71552943e18061fdb44a72eca14ea193e0505a7ead404864f9840e275b49"
    publicKey: "0x5fc1f8dc9f0c03087128e4bd724530e883d7de1a431269876dff9c95b8952f73c7e85ac7b49d85a2ad4950e967319482af435e07a0eab0a98d98449437787a00"


# common parameters to all nodes
besuConfig:
  dataPath: "/data"
  genesisFilePath: "/etc/genesis/genesis.json"
  logging: INFO
  p2p:
    enabled: true
    host: "0.0.0.0"
    port: 30303
    discovery: true
    maxPeers: 25
  rpc:
    enabled: true
    host: "0.0.0.0"
    port: 8545
    api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "WEB3", "PRIV", "PERM"]'
    corsOrigins: '["all"]'
    authenticationEnabled: false
  ws:
    enabled: false
    host: "0.0.0.0"
    port: 8546
    api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "WEB3", "PRIV", "PERM"]'
    authenticationEnabled: false
  graphql:
    enabled: false
    host: "0.0.0.0"
    port: 8547
    corsOrigins: '["all"]'
  txPool:
    retentionHours: 999
    maxSize: 1024
  http:
    allowlist: '["*"]'
  metrics:
    enabled: true
    host: "0.0.0.0"
    port: 9545
  metricsPush:
    enabled: false
    host: "5.5.5.5"
    port: 9091
    interval: 15
    prometheusJob: "besu"
  privacy:
    enabled: false
    url: "http://127.0.0.1:9080"
    precompiledAddress: 9
  permissions:
    enabled: false
    nodes:
      enabled: false
      filePath: "/etc/permissions"
    nodesContract:
      enabled: false
      address: "0x0000000000000000000000000000000000001234"
    accounts:
      enabled: false




