apiVersion: v1
kind: Service
metadata:
  name: {{ template "quorum.name" . }}-cakeshop
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: monitoring
    component: cakeshop
  namespace: monitoring
spec:
  type: NodePort
  selector:
    component: cakeshop
  ports:
    - port: 8999
      targetPort: 8999
      nodePort: 30099
      protocol: TCP
      name: cakeshop
